spring:
  application:
    name: Qatrat7ayat

  datasource:
    url: jdbc:postgresql://localhost:1414/prod_db
    username: postgres
    password: 123
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8888