spring:
  application:
    name: Qatrat7ayat

  datasource:
    url: jdbc:postgresql://localhost:1414/prod_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true

springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger-ui.html

server:
  port: 8081


logging:
  level:
    org.springframework.data.jpa: TRACE
    org.springframework.security: DEBUG

security:
  jwt:
    secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000
    refresh-token:
      expiration: 604800000
