package com.wora.qatrat7ayat.seeders;

import com.wora.qatrat7ayat.models.entities.Hospital;
import com.wora.qatrat7ayat.repositories.HospitalRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@RequiredArgsConstructor
public class HospitalSeeder implements CommandLineRunner {
    private final HospitalRepository hospitalRepository;

    @Override
    public void run(String... args) throws Exception {
        seedHospital();
    }

    private void seedHospital() {
        if (hospitalRepository.count() == 0) {
            List<Hospital> hospitals = List.of(
                    new Hospital(null, "Imzouren (Imzouren)", null),
                    new Hospital(null, "Targuist (Targuist)", null),
                    new Hospital(null, "Mohamed V (Ksar El Kebir)", null),
                    new Hospital(null, "Lalla Meriem (Ksar El Kebir)", null),
                    new Hospital(null, "Abou Kacem Zahraoui (Assilah)", null),
                    new Hospital(null, "Mohammed VI (Assilah)", null),
                    new Hospital(null, "Arrazi (Assilah)", null),
                    new Hospital(null, "Mohamed V (Assilah)", null),
                    new Hospital(null, "Al Kortobi (Assilah)", null),
                    new Hospital(null, "Duc De Tovar (Assilah)", null),
                    new Hospital(null, "Centre d'oncologie (Assilah)", null),
                    new Hospital(null, "Hôpital mère enfant Mohamed VI (Assilah)", null),
                    new Hospital(null, "Hôpital psychiatrique Mohamed VI (Assilah)", null),
                    new Hospital(null, "Hôpital des spécialités Mohamed VI (Assilah)", null),
                    new Hospital(null, "Hôpital Civil (Assilah)", null),
                    new Hospital(null, "Errazi (Assilah)", null),
                    new Hospital(null, "Ben Karrich (Assilah)", null),
                    new Hospital(null, "Hassan II (Assilah)", null),
                    new Hospital(null, "Edderak (Assilah)", null),
                    new Hospital(null, "Saidia (Saidia)", null),
                    new Hospital(null, "Driouch (Driouch)", null),
                    new Hospital(null, "Hassan II (Guercif)", null),
                    new Hospital(null, "Jrada (Jrada)", null),
                    new Hospital(null, "Mohammed VI (Jrada)", null),
                    new Hospital(null, "Hassani (Jrada)", null),
                    new Hospital(null, "Zaio (Zaio)", null),
                    new Hospital(null, "Al Farabi (Zaio)", null),
                    new Hospital(null, "Hôpital Psychiatrique (Zaio)", null),
                    new Hospital(null, "Hôpital des Spécialités (Zaio)", null),
                    new Hospital(null, "Hôpital Mère-Enfant (Zaio)", null),
                    new Hospital(null, "Centre d'oncologie Hassan II (Zaio)", null),
                    new Hospital(null, "HPr Laayoune Sidi Mellouk (Taourirt)", null),
                    new Hospital(null, "Sidi Said (Taourirt)", null),
                    new Hospital(null, "Mohamed V (Taourirt)", null),
                    new Hospital(null, "Pagnon (Taourirt)", null),
                    new Hospital(null, "Moulay Ismail (Taourirt)", null),
                    new Hospital(null, "Centre d'oncologie (Taourirt)", null),
                    new Hospital(null, "Marche Verte (Taourirt)", null),
                    new Hospital(null, "S. Ahmed B. Driss Missouri (Taourirt)", null),
                    new Hospital(null, "Prince My Hassan (Taourirt)", null),
                    new Hospital(null, "Al Ghassani (Taourirt)", null),
                    new Hospital(null, "Ibn Al Baitar (Taourirt)", null),
                    new Hospital(null, "Hôpital d'Oncologie (Taourirt)", null),
                    new Hospital(null, "Hôpital des spécialités (Taourirt)", null),
                    new Hospital(null, "Hôpital Mère-Enfant (Taourirt)", null),
                    new Hospital(null, "Omar Drissi (Taourirt)", null),
                    new Hospital(null, "Ibn Al Khatib (Taourirt)", null),
                    new Hospital(null, "Ibn Al Hassan (Taourirt)", null),
                    new Hospital(null, "20 Aout (Azrou)", null),
                    new Hospital(null, "Mohamed V (Azrou)", null),
                    new Hospital(null, "Hassan II (Taounate)", null),
                    new Hospital(null, "Ibn Baja (Taounate)", null),
                    new Hospital(null, "Al Idrissi (Taounate)", null),
                    new Hospital(null, "Zoubir Skirej (Taounate)", null),
                    new Hospital(null, "Khémisset (Khémisset)", null),
                    new Hospital(null, "Roummani (Khémisset)", null),
                    new Hospital(null, "Tiflet (Tiflet)", null),
                    new Hospital(null, "Ibn Sina (Tiflet)", null),
                    new Hospital(null, "Hôpital Des Spécialités (Tiflet)", null),
                    new Hospital(null, "Maternité Souissi (Tiflet)", null),
                    new Hospital(null, "Hôpital D'enfants (Tiflet)", null),
                    new Hospital(null, "Maternité Orangers (Tiflet)", null),
                    new Hospital(null, "Med Ben Abdellah (Tiflet)", null),
                    new Hospital(null, "My Youssef (Tiflet)", null),
                    new Hospital(null, "Moulay Youssef (Ancien hôpital de Rabat)", null),
                    new Hospital(null, "El Ayachi (Rabat)", null),
                    new Hospital(null, "Moulay Abdellah (Hôp. préféctoral)", null),
                    new Hospital(null, "Arrazi (Rabat)", null),
                    new Hospital(null, "Jorf Elmelha (Rabat)", null),
                    new Hospital(null, "Sidi Kacem (Sidi Kacem)", null),
                    new Hospital(null, "Sidi Slimane (Sidi Slimane)", null),
                    new Hospital(null, "Princesse Lalla Aicha (Ancien Sidi Lahcen)", null),
                    new Hospital(null, "Haut Atlas Central (Demnate)", null),
                    new Hospital(null, "Beni Mellal (Beni Mellal)", null),
                    new Hospital(null, "Moulay Ismail (Beni Mellal)", null),
                    new Hospital(null, "Fquih Ben Salah (Fquih Ben Salah)", null),
                    new Hospital(null, "Souk Sebt (Souk Sebt)", null),
                    new Hospital(null, "Khenifra (Khenifra)", null),
                    new Hospital(null, "M'Rirt (M'Rirt)", null),
                    new Hospital(null, "Mohamed VI (Khenifra)", null),
                    new Hospital(null, "Hassan II (Oued Zem)", null),
                    new Hospital(null, "Benslimane (Hassan II)", null),
                    new Hospital(null, "Berrchid (Berrchid)", null),
                    new Hospital(null, "Errazi (Berrchid)", null),
                    new Hospital(null, "Azemmour (Azemmour)", null),
                    new Hospital(null, "Mohamed V (Azemmour)", null),
                    new Hospital(null, "Mediouna (Mediouna)", null),
                    new Hospital(null, "Tit Mellil (Tit Mellil)", null),
                    new Hospital(null, "My Abdellah (Tit Mellil)", null),
                    new Hospital(null, "Bouskoura (Bouskoura)", null),
                    new Hospital(null, "Prince My Hassan (Bouskoura)", null),
                    new Hospital(null, "Ben Ahmed (Ben Ahmed)", null),
                    new Hospital(null, "Hassan II (Ben Ahmed)", null),
                    new Hospital(null, "Sidi Bennour (Sidi Bennour)", null),
                    new Hospital(null, "Zmamra (Zmamra)", null),
                    new Hospital(null, "20 Aout 1953 (Zmamra)", null),
                    new Hospital(null, "Ibn Rochd (Zmamra)", null),
                    new Hospital(null, "Hôpital D'enfants (Zmamra)", null),
                    new Hospital(null, "My Youssef (Zmamra)", null),
                    new Hospital(null, "Mohamed Baouafi (Zmamra)", null),
                    new Hospital(null, "Mohamed V (Zmamra)", null),
                    new Hospital(null, "El Hassani (Zmamra)", null),
                    new Hospital(null, "Centre de Léprologie (Zmamra)", null),
                    new Hospital(null, "Mohamed Sekkat (Zmamra)", null),
                    new Hospital(null, "Al Mansour (Zmamra)", null),
                    new Hospital(null, "HPr Sidi Moumen (Zmamra)", null),
                    new Hospital(null, "Ben Msick (Zmamra)", null),
                    new Hospital(null, "Sidi Othmane (Zmamra)", null),
                    new Hospital(null, "Mohammed VI (Zmamra)", null),
                    new Hospital(null, "Assalama (Zmamra)", null),
                    new Hospital(null, "Hôpital psychiatrique (Zmamra)", null),
                    new Hospital(null, "Princesse Lalla Khadija (Zmamra)", null),
                    new Hospital(null, "Sidi Med Ben Abdellah (Zmamra)", null),
                    new Hospital(null, "Ibn Tofeil (Zmamra)", null),
                    new Hospital(null, "Ibn Nafis (Zmamra)", null),
                    new Hospital(null, "Hopital Mère-Enfant (Zmamra)", null),
                    new Hospital(null, "Centre d'Hématologie Oncologie (Zmamra)", null),
                    new Hospital(null, "Arrazi (Zmamra)", null),
                    new Hospital(null, "Ibn Zohr (Zmamra)", null),
                    new Hospital(null, "El Antaki (Zmamra)", null),
                    new Hospital(null, "Mhamid (Mhamid)", null),
                    new Hospital(null, "Charifa (Charifa)", null),
                    new Hospital(null, "Saada (Saada)", null),
                    new Hospital(null, "Benguerir (Benguerir)", null),
                    new Hospital(null, "Mohamed V (Benguerir)", null),
                    new Hospital(null, "Aisha (Benguerir)", null),
                    new Hospital(null, "Lalla Hasna (Benguerir)", null),
                    new Hospital(null, "Sghiri Houmman I Ben Maati (Benguerir)", null),
                    new Hospital(null, "My Ali Cherif (Benguerir)", null),
                    new Hospital(null, "Hôpital Amir Soultan Ibn Abdelaziz (Benguerir)", null),
                    new Hospital(null, "20 Aout (Goulmima)", null),
                    new Hospital(null, "Midelt (Midelt)", null),
                    new Hospital(null, "HPr Rich (Midelt)", null),
                    new Hospital(null, "Sidi Hssain Bencer (Midelt)", null),
                    new Hospital(null, "Bougafer (Midelt)", null),
                    new Hospital(null, "HPr Kalaat M'gouna (Tinghir)", null),
                    new Hospital(null, "Tinghir (Tinghir)", null),
                    new Hospital(null, "Ed-Derrak (Tinghir)", null),
                    new Hospital(null, "Hassan II (Tinghir)", null),
                    new Hospital(null, "C. d'Oncologie d'Agadir (Agadir)", null),
                    new Hospital(null, "Mokhtar Soussi (Agadir)", null),
                    new Hospital(null, "Inezgane (Inezgane)", null),
                    new Hospital(null, "Oulad Teima (Oulad Teima)", null),
                    new Hospital(null, "Mokhtar Es-Soussi (Tata)", null),
                    new Hospital(null, "Tata (Tata)", null),
                    new Hospital(null, "Hassan 1er (Tata)", null),
                    new Hospital(null, "Houmman El Fatouaki (Tata)", null),
                    new Hospital(null, "Assa (Assa)", null),
                    new Hospital(null, "Bouizakaren (Bouizakaren)", null),
                    new Hospital(null, "Guelmim (Guelmim)", null),
                    new Hospital(null, "Sidi Ifni (Sidi Ifni)", null),
                    new Hospital(null, "Hassan II (Sidi Ifni)", null),
                    new Hospital(null, "Boujdour (Boujdour)", null),
                    new Hospital(null, "Es-Smara (Es-Smara)", null),
                    new Hospital(null, "My Hassan Ben El Mehdi (Es-Smara)", null),
                    new Hospital(null, "Hassan II (Laayoune)", null)
            );

            hospitalRepository.saveAll(hospitals);
            System.out.println("Hospitals seeded successfully.");
        } else {
            System.out.println("Hospitals already exist, skipping seeding.");
        }
    }
}
